Widgets revamp
maxicarlos08/gphoto2-rs pull request #13
Opened 2022-09-21 22:23 UTC by RReverser

This adds typed variations of widgets, so that it's impossible to pass incompatible value to a widget set_value, or try to access children on non-grouping widget and so on.

More specifically, this adds `widget::{GroupWidget, TextWidget, RangeWidget, ToggleWidget, RadioWidget, ButtonWidget}` types that each provides its own strongly typed API.

All those types inherit from `WidgetBase` that also provides core properties such as `id`, `name` and so on that can be accessed on any of strongly widget types as well.

There is also a `Widget` enum that is simply a container for arbitrary widget and can be matched against or converted into the specific widget type.

Finally, top-level function `config` was updated to return `GroupWidget` and `config_key` has a generic param that allows to immediately specify which widget type you want (since in most cases, when user provides a hardcoded widget name, they likely know its type as well).

This is fairly big change, but I think the ergonomics of statically typed widgets are worth it.

2022-09-22 06:06 UTC, maxicarlos08 commented
Looks good at a first glance, I'll review it later (after school)

2022-09-22 15:24 UTC, maxicarlos08 requested changes

2022-09-22 20:51 UTC, RReverser commented on src/widget.rs
> +  pub fn ty(&self) -> Result<libgphoto2_sys::CameraWidgetType> {
> create a wrapper with perhaps a better naming (no `GP_WIDGET_` prefix) and documentation

TBH I had such enum but I'm not sure if anyone would even need to access those types most of the time - if they want to check widget types, it's better to do so directly by matching the new `Widget` enum. Which is why I made this method public/private forth and back several times 😅

Maybe I should just make it private again, until someone requests this for some good reason.

2022-09-22 20:58 UTC, RReverser commented on src/widget.rs
> +  pub fn set_value(&self, value: &str) -> Result<()> {
Personally I incline towards no - those APIs all seem to fall well under the case of [interior mutability](https://doc.rust-lang.org/reference/interior-mutability.html), sort of like, say, you can do `file.seek(...)` or `file.set_len(...)` on an immutable reference because it doesn't actually mutate the struct itself, and the structs themselves can't be shared across different threads, so there's no conflict possible between different reads/writes.

2022-09-22 20:58 UTC, maxicarlos08 commented on src/widget.rs
> +  pub fn ty(&self) -> Result<libgphoto2_sys::CameraWidgetType> {
> it's better to do so directly by matching the new Widget enum

I realized that just after the submitting the review and reading the PR description to the end.

2022-09-22 21:04 UTC, merged

2022-09-22 21:09 UTC, maxicarlos08 commented
Do you think this should be in the 2.x release?

2022-09-22 21:37 UTC, RReverser commented
> Do you think this should be in the 2.x release?

Completely up to you, really. Although, let me make one more breaking PR before you tag a release :)

2022-09-23 01:54 UTC, RReverser commented
I think I'll send it tomorrow or day after.