Set context Progress functions
maxicarlos08/gphoto2-rs pull request #37
Opened 2022-09-29 06:02 UTC by maxicarlos08

fixes #30

2022-09-30 23:05 UTC, maxicarlos08 commented
Confirmed this works on a real camera.

2022-09-30 23:13 UTC, maxicarlos08 commented
@RReverser would you mind briefly checking if I didn't create any stupid memory related bugs again?

2022-10-01 01:34 UTC, RReverser commented
I want to take a detailed look, but not today - quite late here :)

2022-10-01 12:42 UTC, RReverser requested changes

2022-10-01 12:42 UTC, RReverser commented on src/context.rs
> +        Box::into_raw(progress_functions).cast(),
Leaking memory is problematic for obvious reasons.

Instead, I'd suggest to add `impl Clone for Context` (and perhaps to all other structs where we can do `*_ref()`), so that it's clonable on Rust side by delegating to internal ref-counting.

Then, instead of storing `*mut GPContext` in `Camera`, you can just store a cloned `Context`, which will take care of its own `Drop` too. Less unsafe code, win-win!

Then, you can simply store `Rc<dyn ProgressHandler>` in `Context` too, so it will be counted on every clone and uncounted on every drop, like `GPContext` itself. That way, when the last `Context` is gone, and only then, the underlying memory behind `dyn ProgressHandler` will be freed too.

2022-10-01 13:47 UTC, maxicarlos08 commented on src/context.rs
> +    ($data:expr, $function:ident ($($args:expr$(,)?)+)) => {
Oh I didn't know that existed, thx

2022-10-01 13:50 UTC, RReverser commented
You probably didn't want to commit that JPEG file to the repo :)

2022-10-01 13:51 UTC, maxicarlos08 commented
Shit you saw my desk

2022-10-01 13:57 UTC, RReverser requested changes

2022-10-01 13:57 UTC, RReverser commented on src/context.rs
> +pub(self) use call_progress_func;
I don't think this macro is supposed to be public?

2022-10-01 13:57 UTC, RReverser commented on src/context.rs
> +  pub fn set_progress_functions(&mut self, handler: Box<dyn ProgressHandler>) {
I'd suggest to instead take `impl ProgressHandler` here, and box internally for usage convenience.

2022-10-01 13:57 UTC, RReverser commented on src/context.rs
> +  progress_handler: Option<Rc<Box<dyn ProgressHandler>>>,
As mentioned in the original comment, this can be just `Rc<dyn ProgressHandler>` instead of `Rc<Box<...>>` (pointer to pointer). Especially combined with the suggestion below (`impl ProgressHandler`), this should be easy to create and store transparently to the user.

2022-10-01 13:57 UTC, RReverser commented on src/context.rs
> +    self.progress_handler = Some(Rc::new(handler));
Create local variable first with just `Rc::new(...)`, then do `gp_context_set_progress_funcs`, and then save it in `self.progress_handler`.

That way, you won't need to do `unwrap()` in the code below for an option that you already know has value.

2022-10-01 13:59 UTC, maxicarlos08 commented on src/context.rs
> +pub(self) use call_progress_func;
The macro is only `pub(self)`, so it can only be used inside this module.

2022-10-01 14:02 UTC, maxicarlos08 commented on src/context.rs
> +  pub fn set_progress_functions(&mut self, handler: Box<dyn ProgressHandler>) {
The `impl ProgressHandler` version gives me:

```
error[E0310]: the parameter type `impl ProgressHandler` may not live long enough
   --> src/context.rs:201:42
    |
201 |     self.progress_handler = Some(Rc::new(Box::new(handler)));
    |                                          ^^^^^^^^^^^^^^^^^ ...so that the type `impl ProgressHandler` will meet its required lifetime bounds
    |
help: consider adding an explicit lifetime bound...
    |
174 |   pub fn set_progress_functions(&mut self, handler: impl ProgressHandler + 'static) {
    |                                                                          +++++++++

For more information about this error, try `rustc --explain E0310`.
error: could not compile `gphoto2` due to previous error
```

which is why I kept that `Box`

2022-10-01 14:05 UTC, RReverser commented on src/context.rs
> +  pub fn set_progress_functions(&mut self, handler: Box<dyn ProgressHandler>) {
FWIW Rust compiler is very good with giving suggestions :) As it says, just add `+ 'static`.

2022-10-01 14:05 UTC, RReverser commented on src/context.rs
> +pub(self) use call_progress_func;
But that should be the default anyway - why do you need visibility directive?

2022-10-01 14:07 UTC, RReverser commented
A general question too: does virtual camera not submit events? If it does, can you add tests? Now that we have a test framework, it would be good to leverage it whenever possible :)

2022-10-01 14:12 UTC, maxicarlos08 commented on src/context.rs
> +  pub fn set_progress_functions(&mut self, handler: Box<dyn ProgressHandler>) {
Sorry, but I'm stuck now (Rust compiler wont help me out either)

2022-10-01 14:14 UTC, maxicarlos08 commented
> A general question too: does virtual camera not submit events? If it does, can you add tests? Now that we have a test framework, it would be good to leverage it whenever possible :)

I'll see if I get any events

2022-10-01 14:18 UTC, RReverser commented on examples/camera_progress.rs
> +  progresses: HashMap<u32, ContextProgress>,
This could probably be just a `Vec<ContextProgress>`? Then you can always use `vec.len()` as the next id, and `vec[id]` to get event.

It would mean some ids would get reused when the original progress was already stopped, but I don't suppose it's a problem (once stopped, it shouldn't get any more updates).

2022-10-01 14:21 UTC, maxicarlos08 commented on examples/camera_progress.rs
> +  progresses: HashMap<u32, ContextProgress>,
But then what if:

 - progress 1 starts with ID 1
 - progress 2 starts with ID 2
 - progress 1 ends earilier than 2 and is removed from the Vec
 - progress 3 starts and now also has ID 2

2022-10-01 14:24 UTC, maxicarlos08 commented on examples/camera_progress.rs
> +  progresses: HashMap<u32, ContextProgress>,
Can we be 100% sure that there wont be any concurrent progresses?

2022-10-01 14:25 UTC, maxicarlos08 commented on src/context.rs
> +pub(self) use call_progress_func;
It was because I placed the macro after where it was used, placed it at the start of the file and works without `pub(self)`

ref: https://doc.rust-lang.org/stable/reference/macros-by-example.html#textual-scope

2022-10-01 15:04 UTC, RReverser commented on examples/camera_progress.rs
> +  progresses: HashMap<u32, ContextProgress>,
Ohh yeah good point.

2022-10-01 15:07 UTC, RReverser commented
I'll try to help with Rc<dyn> stuff when I'm back. For now, feel free to revert it and try to add virtual tests instead.

2022-10-01 15:09 UTC, maxicarlos08 commented
> > A general question too: does virtual camera not submit events? If it does, can you add tests? Now that we have a test framework, it would be good to leverage it whenever possible :)
> 
> I'll see if I get any events

I just played around a bit with events on the virtual camera, and I think I found some kind of bug.

The only function that I've found so far that makes events is `camera.summary()` (???). The weird thing is that it outputs these events in an infinite loop:
```
Event: Unknown("PTP Property 5001 changed, \"batterylevel\" to \"50%\"")
Event: Unknown("PTP Property 5003 changed, \"imagesize\" to \"640x480\"")
Event: Unknown("PTP Property 5007 changed, \"f-number\" to \"f/2.8\"")
Event: Unknown("PTP Property 5010 changed, \"exposurecompensation\" to \"0\"")
Event: Unknown("PTP Property 500d changed, \"shutterspeed\" to \"0.0100s\"")
Event: Unknown("PTP Property 5001 changed, \"batterylevel\" to \"50%\"")
Event: Unknown("PTP Property 5003 changed, \"imagesize\" to \"640x480\"")
Event: Unknown("PTP Property 5007 changed, \"f-number\" to \"f/2.8\"")
Event: Unknown("PTP Property 5010 changed, \"exposurecompensation\" to \"0\"")
Event: Unknown("PTP Property 500d changed, \"shutterspeed\" to \"0.0100s\"")
Event: Unknown("PTP Property 5001 changed, \"batterylevel\" to \"50%\"")
Event: Unknown("PTP Property 5003 changed, \"imagesize\" to \"640x480\"")
Event: Unknown("PTP Property 5007 changed, \"f-number\" to \"f/2.8\"")
Event: Unknown("PTP Property 5010 changed, \"exposurecompensation\" to \"0\"")
Event: Unknown("PTP Property 500d changed, \"shutterspeed\" to \"0.0100s\"")
Event: Unknown("PTP Property 5001 changed, \"batterylevel\" to \"50%\"")
Event: Unknown("PTP Property 5003 changed, \"imagesize\" to \"640x480\"")
Event: Unknown("PTP Property 5007 changed, \"f-number\" to \"f/2.8\"")
Event: Unknown("PTP Property 5010 changed, \"exposurecompensation\" to \"0\"")
Event: Unknown("PTP Property 500d changed, \"shutterspeed\" to \"0.0100s\"")
```

2022-10-01 15:52 UTC, RReverser commented
Hmm that's weird but should be unrelated to this PR anyway, right? Those are regular events, not progress updates you want to test here.

2022-10-01 17:29 UTC, RReverser commented
Pushed a change for Rc<dyn> and added a simple test - couldn't get virtual capture_image to emit any progress, but noticed there is some progress reporting for loading camera drivers at least, so I used that for the snapshot.

2022-10-01 17:30 UTC, RReverser commented
Wait, I should probably remove the message from the snapshot though :D (it has a hardcoded path)

2022-10-01 18:42 UTC, RReverser commented
@maxicarlos08 fwiw I think this is good to go.

2022-10-01 19:14 UTC, maxicarlos08 commented
Thanks!

2022-10-01 19:15 UTC, merged